// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: authentications.sql

package sqlcgen

import (
	"context"

	shared "github.com/sonalys/animeman/internal/domain/shared"
)

const createAuthentication = `-- name: CreateAuthentication :one
INSERT INTO authentications (
    id, type, credentials
) VALUES (
    $1, $2, $3
)
RETURNING id, type, credentials
`

type CreateAuthenticationParams struct {
	ID          shared.ID
	Type        AuthType
	Credentials []byte
}

func (q *Queries) CreateAuthentication(ctx context.Context, arg CreateAuthenticationParams) (Authentication, error) {
	row := q.db.QueryRow(ctx, createAuthentication, arg.ID, arg.Type, arg.Credentials)
	var i Authentication
	err := row.Scan(&i.ID, &i.Type, &i.Credentials)
	return i, err
}

const deleteAuthentication = `-- name: DeleteAuthentication :exec
DELETE FROM authentications
WHERE id = $1
`

func (q *Queries) DeleteAuthentication(ctx context.Context, id shared.ID) error {
	_, err := q.db.Exec(ctx, deleteAuthentication, id)
	return err
}

const getAuthentication = `-- name: GetAuthentication :one
SELECT id, type, credentials FROM authentications
WHERE id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetAuthentication(ctx context.Context, id shared.ID) (Authentication, error) {
	row := q.db.QueryRow(ctx, getAuthentication, id)
	var i Authentication
	err := row.Scan(&i.ID, &i.Type, &i.Credentials)
	return i, err
}

const listAuthenticationsByType = `-- name: ListAuthenticationsByType :many
SELECT id, type, credentials FROM authentications
WHERE type = $1
ORDER BY id
`

func (q *Queries) ListAuthenticationsByType(ctx context.Context, type_ AuthType) ([]Authentication, error) {
	rows, err := q.db.Query(ctx, listAuthenticationsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Authentication
	for rows.Next() {
		var i Authentication
		if err := rows.Scan(&i.ID, &i.Type, &i.Credentials); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredentials = `-- name: UpdateCredentials :exec
UPDATE authentications
SET credentials = $2
WHERE id = $1
`

type UpdateCredentialsParams struct {
	ID          shared.ID
	Credentials []byte
}

func (q *Queries) UpdateCredentials(ctx context.Context, arg UpdateCredentialsParams) error {
	_, err := q.db.Exec(ctx, updateCredentials, arg.ID, arg.Credentials)
	return err
}
