// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: collectionFiles.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCollectionFile = `-- name: DeleteCollectionFile :exec
DELETE FROM collection_files WHERE id = $1
`

func (q *Queries) DeleteCollectionFile(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCollectionFile, id)
	return err
}

const getCollectionFileByEpisode = `-- name: GetCollectionFileByEpisode :one
SELECT id, episode_id, season_id, media_id, relative_path, size_bytes, release_group, version, source, video_info, audio_streams, subtitle_streams, chapters, hashes, created_at FROM collection_files 
WHERE episode_id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetCollectionFileByEpisode(ctx context.Context, episodeID string) (CollectionFile, error) {
	row := q.db.QueryRow(ctx, getCollectionFileByEpisode, episodeID)
	var i CollectionFile
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.SeasonID,
		&i.MediaID,
		&i.RelativePath,
		&i.SizeBytes,
		&i.ReleaseGroup,
		&i.Version,
		&i.Source,
		&i.VideoInfo,
		&i.AudioStreams,
		&i.SubtitleStreams,
		&i.Chapters,
		&i.Hashes,
		&i.CreatedAt,
	)
	return i, err
}

const listCollectionFilesBySeason = `-- name: ListCollectionFilesBySeason :many
SELECT id, episode_id, season_id, media_id, relative_path, size_bytes, release_group, version, source, video_info, audio_streams, subtitle_streams, chapters, hashes, created_at FROM collection_files 
WHERE season_id = $1
ORDER BY relative_path ASC
`

func (q *Queries) ListCollectionFilesBySeason(ctx context.Context, seasonID string) ([]CollectionFile, error) {
	rows, err := q.db.Query(ctx, listCollectionFilesBySeason, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionFile
	for rows.Next() {
		var i CollectionFile
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.SeasonID,
			&i.MediaID,
			&i.RelativePath,
			&i.SizeBytes,
			&i.ReleaseGroup,
			&i.Version,
			&i.Source,
			&i.VideoInfo,
			&i.AudioStreams,
			&i.SubtitleStreams,
			&i.Chapters,
			&i.Hashes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionFilesPaginated = `-- name: ListCollectionFilesPaginated :many
SELECT id, episode_id, season_id, media_id, relative_path, size_bytes, release_group, version, source, video_info, audio_streams, subtitle_streams, chapters, hashes, created_at FROM collection_files
WHERE (id) < ($1::uuid)
ORDER BY id DESC
LIMIT $2
`

type ListCollectionFilesPaginatedParams struct {
	Column1 string
	Limit   int32
}

func (q *Queries) ListCollectionFilesPaginated(ctx context.Context, arg ListCollectionFilesPaginatedParams) ([]CollectionFile, error) {
	rows, err := q.db.Query(ctx, listCollectionFilesPaginated, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionFile
	for rows.Next() {
		var i CollectionFile
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.SeasonID,
			&i.MediaID,
			&i.RelativePath,
			&i.SizeBytes,
			&i.ReleaseGroup,
			&i.Version,
			&i.Source,
			&i.VideoInfo,
			&i.AudioStreams,
			&i.SubtitleStreams,
			&i.Chapters,
			&i.Hashes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerCollectionFile = `-- name: RegisterCollectionFile :one
INSERT INTO collection_files (
    id, episode_id, season_id, media_id, relative_path, 
    size_bytes, release_group, version, source,
    video_info, audio_streams, subtitle_streams, chapters, hashes,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, episode_id, season_id, media_id, relative_path, size_bytes, release_group, version, source, video_info, audio_streams, subtitle_streams, chapters, hashes, created_at
`

type RegisterCollectionFileParams struct {
	ID              string
	EpisodeID       string
	SeasonID        string
	MediaID         string
	RelativePath    string
	SizeBytes       int64
	ReleaseGroup    pgtype.Text
	Version         int32
	Source          FileSource
	VideoInfo       []byte
	AudioStreams    []byte
	SubtitleStreams []byte
	Chapters        []byte
	Hashes          []byte
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) RegisterCollectionFile(ctx context.Context, arg RegisterCollectionFileParams) (CollectionFile, error) {
	row := q.db.QueryRow(ctx, registerCollectionFile,
		arg.ID,
		arg.EpisodeID,
		arg.SeasonID,
		arg.MediaID,
		arg.RelativePath,
		arg.SizeBytes,
		arg.ReleaseGroup,
		arg.Version,
		arg.Source,
		arg.VideoInfo,
		arg.AudioStreams,
		arg.SubtitleStreams,
		arg.Chapters,
		arg.Hashes,
		arg.CreatedAt,
	)
	var i CollectionFile
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.SeasonID,
		&i.MediaID,
		&i.RelativePath,
		&i.SizeBytes,
		&i.ReleaseGroup,
		&i.Version,
		&i.Source,
		&i.VideoInfo,
		&i.AudioStreams,
		&i.SubtitleStreams,
		&i.Chapters,
		&i.Hashes,
		&i.CreatedAt,
	)
	return i, err
}

const updateCollectionFile = `-- name: UpdateCollectionFile :one
UPDATE collection_files
SET 
    relative_path = $2, 
    size_bytes = $3, 
    version = $4,
    video_info = $5,
    audio_streams = $6,
    subtitle_streams = $7,
    chapters = $8,
    hashes = $9
WHERE id = $1
RETURNING id, episode_id, season_id, media_id, relative_path, size_bytes, release_group, version, source, video_info, audio_streams, subtitle_streams, chapters, hashes, created_at
`

type UpdateCollectionFileParams struct {
	ID              string
	RelativePath    string
	SizeBytes       int64
	Version         int32
	VideoInfo       []byte
	AudioStreams    []byte
	SubtitleStreams []byte
	Chapters        []byte
	Hashes          []byte
}

func (q *Queries) UpdateCollectionFile(ctx context.Context, arg UpdateCollectionFileParams) (CollectionFile, error) {
	row := q.db.QueryRow(ctx, updateCollectionFile,
		arg.ID,
		arg.RelativePath,
		arg.SizeBytes,
		arg.Version,
		arg.VideoInfo,
		arg.AudioStreams,
		arg.SubtitleStreams,
		arg.Chapters,
		arg.Hashes,
	)
	var i CollectionFile
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.SeasonID,
		&i.MediaID,
		&i.RelativePath,
		&i.SizeBytes,
		&i.ReleaseGroup,
		&i.Version,
		&i.Source,
		&i.VideoInfo,
		&i.AudioStreams,
		&i.SubtitleStreams,
		&i.Chapters,
		&i.Hashes,
		&i.CreatedAt,
	)
	return i, err
}
