// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collectionFiles.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sonalys/animeman/internal/adapters/postgres/dtos"
	shared "github.com/sonalys/animeman/internal/domain/shared"
)

const deleteCollectionFile = `-- name: DeleteCollectionFile :exec
DELETE FROM collection_files WHERE id = $1
`

func (q *Queries) DeleteCollectionFile(ctx context.Context, id shared.ID) error {
	_, err := q.db.Exec(ctx, deleteCollectionFile, id)
	return err
}

const getCollectionFile = `-- name: GetCollectionFile :one
SELECT id, episode_id, season_id, media_id, relative_path, size_bytes, release_group, version, source, video_info, audio_streams, subtitle_streams, chapters, hashes, created_at FROM collection_files 
WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetCollectionFile(ctx context.Context, id shared.ID) (CollectionFile, error) {
	row := q.db.QueryRow(ctx, getCollectionFile, id)
	var i CollectionFile
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.SeasonID,
		&i.MediaID,
		&i.RelativePath,
		&i.SizeBytes,
		&i.ReleaseGroup,
		&i.Version,
		&i.Source,
		&i.VideoInfo,
		&i.AudioStreams,
		&i.SubtitleStreams,
		&i.Chapters,
		&i.Hashes,
		&i.CreatedAt,
	)
	return i, err
}

const getCollectionFileByEpisode = `-- name: GetCollectionFileByEpisode :one
SELECT id, episode_id, season_id, media_id, relative_path, size_bytes, release_group, version, source, video_info, audio_streams, subtitle_streams, chapters, hashes, created_at FROM collection_files 
WHERE episode_id = $1 FOR UPDATE
`

func (q *Queries) GetCollectionFileByEpisode(ctx context.Context, episodeID shared.ID) (CollectionFile, error) {
	row := q.db.QueryRow(ctx, getCollectionFileByEpisode, episodeID)
	var i CollectionFile
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.SeasonID,
		&i.MediaID,
		&i.RelativePath,
		&i.SizeBytes,
		&i.ReleaseGroup,
		&i.Version,
		&i.Source,
		&i.VideoInfo,
		&i.AudioStreams,
		&i.SubtitleStreams,
		&i.Chapters,
		&i.Hashes,
		&i.CreatedAt,
	)
	return i, err
}

const listCollectionFilesBySeason = `-- name: ListCollectionFilesBySeason :many
SELECT id, episode_id, season_id, media_id, relative_path, size_bytes, release_group, version, source, video_info, audio_streams, subtitle_streams, chapters, hashes, created_at FROM collection_files 
WHERE season_id = $1
ORDER BY relative_path ASC
`

func (q *Queries) ListCollectionFilesBySeason(ctx context.Context, seasonID shared.ID) ([]CollectionFile, error) {
	rows, err := q.db.Query(ctx, listCollectionFilesBySeason, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionFile
	for rows.Next() {
		var i CollectionFile
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.SeasonID,
			&i.MediaID,
			&i.RelativePath,
			&i.SizeBytes,
			&i.ReleaseGroup,
			&i.Version,
			&i.Source,
			&i.VideoInfo,
			&i.AudioStreams,
			&i.SubtitleStreams,
			&i.Chapters,
			&i.Hashes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionFilesPaginated = `-- name: ListCollectionFilesPaginated :many
SELECT id, episode_id, season_id, media_id, relative_path, size_bytes, release_group, version, source, video_info, audio_streams, subtitle_streams, chapters, hashes, created_at FROM collection_files
WHERE 
    $1::uuid is NULL OR id < $1::uuid AND
    $2::uuid is NULL OR collection_id = $2::uuid
ORDER BY id DESC
LIMIT $3::integer
`

type ListCollectionFilesPaginatedParams struct {
	LastID       pgtype.UUID
	CollectionID pgtype.UUID
	Limit        pgtype.Int4
}

func (q *Queries) ListCollectionFilesPaginated(ctx context.Context, arg ListCollectionFilesPaginatedParams) ([]CollectionFile, error) {
	rows, err := q.db.Query(ctx, listCollectionFilesPaginated, arg.LastID, arg.CollectionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionFile
	for rows.Next() {
		var i CollectionFile
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.SeasonID,
			&i.MediaID,
			&i.RelativePath,
			&i.SizeBytes,
			&i.ReleaseGroup,
			&i.Version,
			&i.Source,
			&i.VideoInfo,
			&i.AudioStreams,
			&i.SubtitleStreams,
			&i.Chapters,
			&i.Hashes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerCollectionFile = `-- name: RegisterCollectionFile :one
INSERT INTO collection_files (
    id, episode_id, season_id, media_id, relative_path, 
    size_bytes, release_group, version, source,
    video_info, audio_streams, subtitle_streams, chapters, hashes,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, episode_id, season_id, media_id, relative_path, size_bytes, release_group, version, source, video_info, audio_streams, subtitle_streams, chapters, hashes, created_at
`

type RegisterCollectionFileParams struct {
	ID              shared.ID
	EpisodeID       shared.ID
	SeasonID        shared.ID
	MediaID         shared.ID
	RelativePath    string
	SizeBytes       int64
	ReleaseGroup    pgtype.Text
	Version         int32
	Source          FileSource
	VideoInfo       dtos.VideoInfo
	AudioStreams    dtos.AudioStreams
	SubtitleStreams dtos.Subtitles
	Chapters        dtos.Chapters
	Hashes          dtos.Hashes
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) RegisterCollectionFile(ctx context.Context, arg RegisterCollectionFileParams) (CollectionFile, error) {
	row := q.db.QueryRow(ctx, registerCollectionFile,
		arg.ID,
		arg.EpisodeID,
		arg.SeasonID,
		arg.MediaID,
		arg.RelativePath,
		arg.SizeBytes,
		arg.ReleaseGroup,
		arg.Version,
		arg.Source,
		arg.VideoInfo,
		arg.AudioStreams,
		arg.SubtitleStreams,
		arg.Chapters,
		arg.Hashes,
		arg.CreatedAt,
	)
	var i CollectionFile
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.SeasonID,
		&i.MediaID,
		&i.RelativePath,
		&i.SizeBytes,
		&i.ReleaseGroup,
		&i.Version,
		&i.Source,
		&i.VideoInfo,
		&i.AudioStreams,
		&i.SubtitleStreams,
		&i.Chapters,
		&i.Hashes,
		&i.CreatedAt,
	)
	return i, err
}

const updateCollectionFile = `-- name: UpdateCollectionFile :one
UPDATE collection_files
SET 
    relative_path = $2, 
    size_bytes = $3, 
    version = $4,
    video_info = $5,
    audio_streams = $6,
    subtitle_streams = $7,
    chapters = $8,
    hashes = $9
WHERE id = $1
RETURNING id, episode_id, season_id, media_id, relative_path, size_bytes, release_group, version, source, video_info, audio_streams, subtitle_streams, chapters, hashes, created_at
`

type UpdateCollectionFileParams struct {
	ID              shared.ID
	RelativePath    string
	SizeBytes       int64
	Version         int32
	VideoInfo       dtos.VideoInfo
	AudioStreams    dtos.AudioStreams
	SubtitleStreams dtos.Subtitles
	Chapters        dtos.Chapters
	Hashes          dtos.Hashes
}

func (q *Queries) UpdateCollectionFile(ctx context.Context, arg UpdateCollectionFileParams) (CollectionFile, error) {
	row := q.db.QueryRow(ctx, updateCollectionFile,
		arg.ID,
		arg.RelativePath,
		arg.SizeBytes,
		arg.Version,
		arg.VideoInfo,
		arg.AudioStreams,
		arg.SubtitleStreams,
		arg.Chapters,
		arg.Hashes,
	)
	var i CollectionFile
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.SeasonID,
		&i.MediaID,
		&i.RelativePath,
		&i.SizeBytes,
		&i.ReleaseGroup,
		&i.Version,
		&i.Source,
		&i.VideoInfo,
		&i.AudioStreams,
		&i.SubtitleStreams,
		&i.Chapters,
		&i.Hashes,
		&i.CreatedAt,
	)
	return i, err
}
