// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: indexerClients.sql

package sqlcgen

import (
	"context"

	shared "github.com/sonalys/animeman/internal/domain/shared"
)

const createIndexerClient = `-- name: CreateIndexerClient :one
INSERT INTO indexer_clients (
    id, owner_id, address, type, auth_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, owner_id, address, type, auth_id
`

type CreateIndexerClientParams struct {
	ID      shared.ID
	OwnerID shared.ID
	Address string
	Type    IndexerClientType
	AuthID  shared.ID
}

func (q *Queries) CreateIndexerClient(ctx context.Context, arg CreateIndexerClientParams) (IndexerClient, error) {
	row := q.db.QueryRow(ctx, createIndexerClient,
		arg.ID,
		arg.OwnerID,
		arg.Address,
		arg.Type,
		arg.AuthID,
	)
	var i IndexerClient
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Address,
		&i.Type,
		&i.AuthID,
	)
	return i, err
}

const deleteIndexerClient = `-- name: DeleteIndexerClient :exec
DELETE FROM indexer_clients
WHERE id = $1
`

func (q *Queries) DeleteIndexerClient(ctx context.Context, id shared.ID) error {
	_, err := q.db.Exec(ctx, deleteIndexerClient, id)
	return err
}

const getIndexerClient = `-- name: GetIndexerClient :one
SELECT 
    c.id, c.owner_id, c.address, c.type,
    a.id as auth_id, a.type as auth_type, a.credentials as auth_credentials
FROM indexer_clients c
JOIN authentications a ON c.auth_id = a.id
WHERE c.id = $1 LIMIT 1 FOR UPDATE
`

type GetIndexerClientRow struct {
	ID              shared.ID
	OwnerID         shared.ID
	Address         string
	Type            IndexerClientType
	AuthID          shared.ID
	AuthType        AuthType
	AuthCredentials []byte
}

func (q *Queries) GetIndexerClient(ctx context.Context, id shared.ID) (GetIndexerClientRow, error) {
	row := q.db.QueryRow(ctx, getIndexerClient, id)
	var i GetIndexerClientRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Address,
		&i.Type,
		&i.AuthID,
		&i.AuthType,
		&i.AuthCredentials,
	)
	return i, err
}

const listIndexerClientsByOwner = `-- name: ListIndexerClientsByOwner :many
SELECT 
    c.id, c.owner_id, c.address, c.type,
    a.id as auth_id, a.type as auth_type, a.credentials as auth_credentials
FROM indexer_clients c
JOIN authentications a ON c.auth_id = a.id
WHERE c.owner_id = $1
ORDER BY c.id ASC
`

type ListIndexerClientsByOwnerRow struct {
	ID              shared.ID
	OwnerID         shared.ID
	Address         string
	Type            IndexerClientType
	AuthID          shared.ID
	AuthType        AuthType
	AuthCredentials []byte
}

func (q *Queries) ListIndexerClientsByOwner(ctx context.Context, ownerID shared.ID) ([]ListIndexerClientsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listIndexerClientsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIndexerClientsByOwnerRow
	for rows.Next() {
		var i ListIndexerClientsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Address,
			&i.Type,
			&i.AuthID,
			&i.AuthType,
			&i.AuthCredentials,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIndexerAddress = `-- name: UpdateIndexerAddress :exec
UPDATE indexer_clients
SET address = $2
WHERE id = $1
`

type UpdateIndexerAddressParams struct {
	ID      shared.ID
	Address string
}

func (q *Queries) UpdateIndexerAddress(ctx context.Context, arg UpdateIndexerAddressParams) error {
	_, err := q.db.Exec(ctx, updateIndexerAddress, arg.ID, arg.Address)
	return err
}
