// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orchestration.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	shared "github.com/sonalys/animeman/internal/domain/shared"
)

const addTaskLog = `-- name: AddTaskLog :exec
INSERT INTO task_logs (
    id, task_id, level, message, trace_id, span_id, created_at
) VALUES (
    $1, $2, $3::log_level, $4, $5, $6, $7
)
`

type AddTaskLogParams struct {
	ID        shared.ID
	TaskID    shared.ID
	Level     LogLevel
	Message   string
	TraceID   pgtype.Text
	SpanID    pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) AddTaskLog(ctx context.Context, arg AddTaskLogParams) error {
	_, err := q.db.Exec(ctx, addTaskLog,
		arg.ID,
		arg.TaskID,
		arg.Level,
		arg.Message,
		arg.TraceID,
		arg.SpanID,
		arg.CreatedAt,
	)
	return err
}

const claimNextTask = `-- name: ClaimNextTask :one
UPDATE orchestration_tasks
SET 
    status = 'running',
    expires_at = NOW() + $1::interval,
    updated_at = NOW()
WHERE id = (
    SELECT id 
    FROM orchestration_tasks 
    WHERE (
        (status = 'pending' AND (next_retry_at IS NULL OR next_retry_at <= NOW()))
        OR 
        (status = 'running' AND expires_at <= NOW())
    )
    ORDER BY created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, task_type, status, payload, retry_count, max_retries, next_retry_at, trace_id, span_id, expires_at, created_at, updated_at
`

// Claims a task if it is pending/retrying OR if it has expired (crashed)
func (q *Queries) ClaimNextTask(ctx context.Context, timeoutInterval pgtype.Interval) (OrchestrationTask, error) {
	row := q.db.QueryRow(ctx, claimNextTask, timeoutInterval)
	var i OrchestrationTask
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Status,
		&i.Payload,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.TraceID,
		&i.SpanID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeTask = `-- name: CompleteTask :exec
UPDATE orchestration_tasks
SET status = 'completed', expires_at = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CompleteTask(ctx context.Context, id shared.ID) error {
	_, err := q.db.Exec(ctx, completeTask, id)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO orchestration_tasks (
    id, task_type, status, payload, retry_count, max_retries, 
    next_retry_at, trace_id, span_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, 
    $7, $8, $9, $10, $11
) RETURNING id, task_type, status, payload, retry_count, max_retries, next_retry_at, trace_id, span_id, expires_at, created_at, updated_at
`

type CreateTaskParams struct {
	ID          shared.ID
	TaskType    string
	Status      TaskStatus
	Payload     []byte
	RetryCount  int32
	MaxRetries  int32
	NextRetryAt pgtype.Timestamptz
	TraceID     pgtype.Text
	SpanID      pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (OrchestrationTask, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.TaskType,
		arg.Status,
		arg.Payload,
		arg.RetryCount,
		arg.MaxRetries,
		arg.NextRetryAt,
		arg.TraceID,
		arg.SpanID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i OrchestrationTask
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Status,
		&i.Payload,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.TraceID,
		&i.SpanID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failTask = `-- name: FailTask :exec
UPDATE orchestration_tasks
SET 
    status = CASE WHEN retry_count < max_retries THEN 'pending'::text ELSE 'failed'::text END,
    retry_count = retry_count + 1,
    next_retry_at = $1,
    expires_at = NULL,
    updated_at = NOW()
WHERE id = $2
`

type FailTaskParams struct {
	NextRetryAt pgtype.Timestamptz
	ID          shared.ID
}

func (q *Queries) FailTask(ctx context.Context, arg FailTaskParams) error {
	_, err := q.db.Exec(ctx, failTask, arg.NextRetryAt, arg.ID)
	return err
}

const listAllLogsPaginated = `-- name: ListAllLogsPaginated :many
SELECT id, task_id, level, message, trace_id, span_id, created_at FROM task_logs
WHERE id > $1
ORDER BY id ASC
LIMIT $2
`

type ListAllLogsPaginatedParams struct {
	LastID   shared.ID
	PageSize int32
}

// Global log feed for the dashboard.
func (q *Queries) ListAllLogsPaginated(ctx context.Context, arg ListAllLogsPaginatedParams) ([]TaskLog, error) {
	rows, err := q.db.Query(ctx, listAllLogsPaginated, arg.LastID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskLog
	for rows.Next() {
		var i TaskLog
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Level,
			&i.Message,
			&i.TraceID,
			&i.SpanID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskLogsPaginated = `-- name: ListTaskLogsPaginated :many
SELECT id, task_id, level, message, trace_id, span_id, created_at FROM task_logs
WHERE task_id = $1
  AND id > $2
ORDER BY id ASC
LIMIT $3
`

type ListTaskLogsPaginatedParams struct {
	TaskID   shared.ID
	LastID   shared.ID
	PageSize int32
}

// Provides a list of logs for a specific task with pagination.
func (q *Queries) ListTaskLogsPaginated(ctx context.Context, arg ListTaskLogsPaginatedParams) ([]TaskLog, error) {
	rows, err := q.db.Query(ctx, listTaskLogsPaginated, arg.TaskID, arg.LastID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskLog
	for rows.Next() {
		var i TaskLog
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Level,
			&i.Message,
			&i.TraceID,
			&i.SpanID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatusPaginated = `-- name: ListTasksByStatusPaginated :many
SELECT id, task_type, status, payload, retry_count, max_retries, next_retry_at, trace_id, span_id, expires_at, created_at, updated_at FROM orchestration_tasks
WHERE status = $1 
  AND id > $2
ORDER BY id ASC
LIMIT $3
`

type ListTasksByStatusPaginatedParams struct {
	Status   TaskStatus
	LastID   shared.ID
	PageSize int32
}

func (q *Queries) ListTasksByStatusPaginated(ctx context.Context, arg ListTasksByStatusPaginatedParams) ([]OrchestrationTask, error) {
	rows, err := q.db.Query(ctx, listTasksByStatusPaginated, arg.Status, arg.LastID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrchestrationTask
	for rows.Next() {
		var i OrchestrationTask
		if err := rows.Scan(
			&i.ID,
			&i.TaskType,
			&i.Status,
			&i.Payload,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.TraceID,
			&i.SpanID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksPaginated = `-- name: ListTasksPaginated :many
SELECT id, task_type, status, payload, retry_count, max_retries, next_retry_at, trace_id, span_id, expires_at, created_at, updated_at FROM orchestration_tasks
WHERE id > $1
ORDER BY id ASC
LIMIT $2
`

type ListTasksPaginatedParams struct {
	LastID   shared.ID
	PageSize int32
}

// Uses keyset pagination. Provide a zero UUID for the first page.
func (q *Queries) ListTasksPaginated(ctx context.Context, arg ListTasksPaginatedParams) ([]OrchestrationTask, error) {
	rows, err := q.db.Query(ctx, listTasksPaginated, arg.LastID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrchestrationTask
	for rows.Next() {
		var i OrchestrationTask
		if err := rows.Scan(
			&i.ID,
			&i.TaskType,
			&i.Status,
			&i.Payload,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.TraceID,
			&i.SpanID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateLogs = `-- name: RotateLogs :exec
DELETE FROM task_logs
WHERE created_at < (NOW() - $1::interval)
   OR id NOT IN (
       SELECT id FROM task_logs
       ORDER BY created_at DESC
       LIMIT $2
   )
`

type RotateLogsParams struct {
	RetentionInterval pgtype.Interval
	MaxLogs           int32
}

// Optimized for your idx_task_logs_rotation index.
// Deletes logs based on time AND a hard count limit.
func (q *Queries) RotateLogs(ctx context.Context, arg RotateLogsParams) error {
	_, err := q.db.Exec(ctx, rotateLogs, arg.RetentionInterval, arg.MaxLogs)
	return err
}
