// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: qualityProfiles.sql

package sqlcgen

import (
	"context"
)

const createQualityProfile = `-- name: CreateQualityProfile :one
INSERT INTO quality_profiles (
    id, name, min_resolution, max_resolution, 
    codec_preference, release_group_preference
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, name, min_resolution, max_resolution, codec_preference, release_group_preference
`

type CreateQualityProfileParams struct {
	ID                     string
	Name                   string
	MinResolution          Resolution
	MaxResolution          Resolution
	CodecPreference        []VideoCodec
	ReleaseGroupPreference []string
}

func (q *Queries) CreateQualityProfile(ctx context.Context, arg CreateQualityProfileParams) (QualityProfile, error) {
	row := q.db.QueryRow(ctx, createQualityProfile,
		arg.ID,
		arg.Name,
		arg.MinResolution,
		arg.MaxResolution,
		arg.CodecPreference,
		arg.ReleaseGroupPreference,
	)
	var i QualityProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MinResolution,
		&i.MaxResolution,
		&i.CodecPreference,
		&i.ReleaseGroupPreference,
	)
	return i, err
}

const deleteQualityProfile = `-- name: DeleteQualityProfile :exec
DELETE FROM quality_profiles
WHERE id = $1
`

func (q *Queries) DeleteQualityProfile(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteQualityProfile, id)
	return err
}

const getQualityProfile = `-- name: GetQualityProfile :one
SELECT id, name, min_resolution, max_resolution, codec_preference, release_group_preference FROM quality_profiles
WHERE id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetQualityProfile(ctx context.Context, id string) (QualityProfile, error) {
	row := q.db.QueryRow(ctx, getQualityProfile, id)
	var i QualityProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MinResolution,
		&i.MaxResolution,
		&i.CodecPreference,
		&i.ReleaseGroupPreference,
	)
	return i, err
}

const listQualityProfiles = `-- name: ListQualityProfiles :many
SELECT id, name, min_resolution, max_resolution, codec_preference, release_group_preference FROM quality_profiles
ORDER BY name ASC
`

func (q *Queries) ListQualityProfiles(ctx context.Context) ([]QualityProfile, error) {
	rows, err := q.db.Query(ctx, listQualityProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QualityProfile
	for rows.Next() {
		var i QualityProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MinResolution,
			&i.MaxResolution,
			&i.CodecPreference,
			&i.ReleaseGroupPreference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQualityProfile = `-- name: UpdateQualityProfile :one
UPDATE quality_profiles
SET 
    name = $2,
    min_resolution = $3,
    max_resolution = $4,
    codec_preference = $5,
    release_group_preference = $6
WHERE id = $1
RETURNING id, name, min_resolution, max_resolution, codec_preference, release_group_preference
`

type UpdateQualityProfileParams struct {
	ID                     string
	Name                   string
	MinResolution          Resolution
	MaxResolution          Resolution
	CodecPreference        []VideoCodec
	ReleaseGroupPreference []string
}

func (q *Queries) UpdateQualityProfile(ctx context.Context, arg UpdateQualityProfileParams) (QualityProfile, error) {
	row := q.db.QueryRow(ctx, updateQualityProfile,
		arg.ID,
		arg.Name,
		arg.MinResolution,
		arg.MaxResolution,
		arg.CodecPreference,
		arg.ReleaseGroupPreference,
	)
	var i QualityProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MinResolution,
		&i.MaxResolution,
		&i.CodecPreference,
		&i.ReleaseGroupPreference,
	)
	return i, err
}
