// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sqlcgen

import (
	"context"
)

const createAnimeList = `-- name: CreateAnimeList :one

INSERT INTO anime_lists (id, owner_id, remote_username, source)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, remote_username, source
`

type CreateAnimeListParams struct {
	ID             string
	OwnerID        string
	RemoteUsername string
	Source         AnimeListSource
}

// --- Anime Lists ---
func (q *Queries) CreateAnimeList(ctx context.Context, arg CreateAnimeListParams) (AnimeList, error) {
	row := q.db.QueryRow(ctx, createAnimeList,
		arg.ID,
		arg.OwnerID,
		arg.RemoteUsername,
		arg.Source,
	)
	var i AnimeList
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.RemoteUsername,
		&i.Source,
	)
	return i, err
}

const createImportConfiguration = `-- name: CreateImportConfiguration :one

INSERT INTO import_configurations (
    id, owner_id, anime_list_id, torrent_client_id, prowlarr_configuration_id
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, anime_list_id, torrent_client_id, prowlarr_configuration_id
`

type CreateImportConfigurationParams struct {
	ID                      string
	OwnerID                 string
	AnimeListID             string
	TorrentClientID         string
	ProwlarrConfigurationID string
}

// --- Import Configurations ---
func (q *Queries) CreateImportConfiguration(ctx context.Context, arg CreateImportConfigurationParams) (ImportConfiguration, error) {
	row := q.db.QueryRow(ctx, createImportConfiguration,
		arg.ID,
		arg.OwnerID,
		arg.AnimeListID,
		arg.TorrentClientID,
		arg.ProwlarrConfigurationID,
	)
	var i ImportConfiguration
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AnimeListID,
		&i.TorrentClientID,
		&i.ProwlarrConfigurationID,
	)
	return i, err
}

const createProwlarrConfiguration = `-- name: CreateProwlarrConfiguration :one

INSERT INTO prowlarr_configurations (id, owner_id, host, api_key)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, host, api_key
`

type CreateProwlarrConfigurationParams struct {
	ID      string
	OwnerID string
	Host    string
	ApiKey  string
}

// --- Prowlarr Configurations ---
func (q *Queries) CreateProwlarrConfiguration(ctx context.Context, arg CreateProwlarrConfigurationParams) (ProwlarrConfiguration, error) {
	row := q.db.QueryRow(ctx, createProwlarrConfiguration,
		arg.ID,
		arg.OwnerID,
		arg.Host,
		arg.ApiKey,
	)
	var i ProwlarrConfiguration
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Host,
		&i.ApiKey,
	)
	return i, err
}

const createTorrentClient = `-- name: CreateTorrentClient :one

INSERT INTO torrent_clients (id, owner_id, source, host, username, password)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, source, host, username, password
`

type CreateTorrentClientParams struct {
	ID       string
	OwnerID  string
	Source   TorrentClientSource
	Host     string
	Username string
	Password string
}

// --- Torrent Clients ---
func (q *Queries) CreateTorrentClient(ctx context.Context, arg CreateTorrentClientParams) (TorrentClient, error) {
	row := q.db.QueryRow(ctx, createTorrentClient,
		arg.ID,
		arg.OwnerID,
		arg.Source,
		arg.Host,
		arg.Username,
		arg.Password,
	)
	var i TorrentClient
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Source,
		&i.Host,
		&i.Username,
		&i.Password,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, username, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, password_hash
`

type CreateUserParams struct {
	ID           string
	Username     string
	PasswordHash string
}

// --- Users ---
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const deleteAnimeList = `-- name: DeleteAnimeList :exec
DELETE FROM anime_lists WHERE source = $1 AND remote_username = $2
`

type DeleteAnimeListParams struct {
	Source         AnimeListSource
	RemoteUsername string
}

func (q *Queries) DeleteAnimeList(ctx context.Context, arg DeleteAnimeListParams) error {
	_, err := q.db.Exec(ctx, deleteAnimeList, arg.Source, arg.RemoteUsername)
	return err
}

const deleteImportConfiguration = `-- name: DeleteImportConfiguration :exec
DELETE FROM import_configurations 
WHERE anime_list_id = $1 AND torrent_client_id = $2
`

type DeleteImportConfigurationParams struct {
	AnimeListID     string
	TorrentClientID string
}

func (q *Queries) DeleteImportConfiguration(ctx context.Context, arg DeleteImportConfigurationParams) error {
	_, err := q.db.Exec(ctx, deleteImportConfiguration, arg.AnimeListID, arg.TorrentClientID)
	return err
}

const deleteProwlarrConfiguration = `-- name: DeleteProwlarrConfiguration :exec
DELETE FROM prowlarr_configurations WHERE id = $1
`

func (q *Queries) DeleteProwlarrConfiguration(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProwlarrConfiguration, id)
	return err
}

const deleteTorrentClient = `-- name: DeleteTorrentClient :exec
DELETE FROM torrent_clients WHERE host = $1
`

func (q *Queries) DeleteTorrentClient(ctx context.Context, host string) error {
	_, err := q.db.Exec(ctx, deleteTorrentClient, host)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAnimeList = `-- name: GetAnimeList :one
SELECT id, owner_id, remote_username, source FROM anime_lists 
WHERE source = $1 AND remote_username = $2 LIMIT 1
`

type GetAnimeListParams struct {
	Source         AnimeListSource
	RemoteUsername string
}

// Lookup by the unique composite primary key
func (q *Queries) GetAnimeList(ctx context.Context, arg GetAnimeListParams) (AnimeList, error) {
	row := q.db.QueryRow(ctx, getAnimeList, arg.Source, arg.RemoteUsername)
	var i AnimeList
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.RemoteUsername,
		&i.Source,
	)
	return i, err
}

const getImportConfiguration = `-- name: GetImportConfiguration :one
SELECT id, owner_id, anime_list_id, torrent_client_id, prowlarr_configuration_id FROM import_configurations 
WHERE anime_list_id = $1 AND torrent_client_id = $2 LIMIT 1
`

type GetImportConfigurationParams struct {
	AnimeListID     string
	TorrentClientID string
}

// Lookup by unique composite tuple
func (q *Queries) GetImportConfiguration(ctx context.Context, arg GetImportConfigurationParams) (ImportConfiguration, error) {
	row := q.db.QueryRow(ctx, getImportConfiguration, arg.AnimeListID, arg.TorrentClientID)
	var i ImportConfiguration
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AnimeListID,
		&i.TorrentClientID,
		&i.ProwlarrConfigurationID,
	)
	return i, err
}

const getProwlarrConfigurationByOwner = `-- name: GetProwlarrConfigurationByOwner :one
SELECT id, owner_id, host, api_key FROM prowlarr_configurations WHERE owner_id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetProwlarrConfigurationByOwner(ctx context.Context, ownerID string) (ProwlarrConfiguration, error) {
	row := q.db.QueryRow(ctx, getProwlarrConfigurationByOwner, ownerID)
	var i ProwlarrConfiguration
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Host,
		&i.ApiKey,
	)
	return i, err
}

const getTorrentClientByHost = `-- name: GetTorrentClientByHost :one
SELECT id, owner_id, source, host, username, password FROM torrent_clients WHERE host = $1 LIMIT 1
`

func (q *Queries) GetTorrentClientByHost(ctx context.Context, host string) (TorrentClient, error) {
	row := q.db.QueryRow(ctx, getTorrentClientByHost, host)
	var i TorrentClient
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Source,
		&i.Host,
		&i.Username,
		&i.Password,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, password_hash FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const listAnimeListsByOwner = `-- name: ListAnimeListsByOwner :many
SELECT id, owner_id, remote_username, source FROM anime_lists WHERE owner_id = $1
`

func (q *Queries) ListAnimeListsByOwner(ctx context.Context, ownerID string) ([]AnimeList, error) {
	rows, err := q.db.Query(ctx, listAnimeListsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnimeList
	for rows.Next() {
		var i AnimeList
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.RemoteUsername,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTorrentClientsByOwner = `-- name: ListTorrentClientsByOwner :many
SELECT id, owner_id, source, host, username, password FROM torrent_clients WHERE owner_id = $1
`

func (q *Queries) ListTorrentClientsByOwner(ctx context.Context, ownerID string) ([]TorrentClient, error) {
	rows, err := q.db.Query(ctx, listTorrentClientsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TorrentClient
	for rows.Next() {
		var i TorrentClient
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Source,
			&i.Host,
			&i.Username,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnimeListOwner = `-- name: UpdateAnimeListOwner :one
UPDATE anime_lists 
SET owner_id = $3
WHERE source = $1 AND remote_username = $2
RETURNING id, owner_id, remote_username, source
`

type UpdateAnimeListOwnerParams struct {
	Source         AnimeListSource
	RemoteUsername string
	OwnerID        string
}

func (q *Queries) UpdateAnimeListOwner(ctx context.Context, arg UpdateAnimeListOwnerParams) (AnimeList, error) {
	row := q.db.QueryRow(ctx, updateAnimeListOwner, arg.Source, arg.RemoteUsername, arg.OwnerID)
	var i AnimeList
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.RemoteUsername,
		&i.Source,
	)
	return i, err
}

const updateImportProwlarrConfig = `-- name: UpdateImportProwlarrConfig :one
UPDATE import_configurations
SET prowlarr_configuration_id = $3
WHERE anime_list_id = $1 AND torrent_client_id = $2
RETURNING id, owner_id, anime_list_id, torrent_client_id, prowlarr_configuration_id
`

type UpdateImportProwlarrConfigParams struct {
	AnimeListID             string
	TorrentClientID         string
	ProwlarrConfigurationID string
}

func (q *Queries) UpdateImportProwlarrConfig(ctx context.Context, arg UpdateImportProwlarrConfigParams) (ImportConfiguration, error) {
	row := q.db.QueryRow(ctx, updateImportProwlarrConfig, arg.AnimeListID, arg.TorrentClientID, arg.ProwlarrConfigurationID)
	var i ImportConfiguration
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AnimeListID,
		&i.TorrentClientID,
		&i.ProwlarrConfigurationID,
	)
	return i, err
}

const updateProwlarrConfiguration = `-- name: UpdateProwlarrConfiguration :one
UPDATE prowlarr_configurations
SET 
    api_key = $2,
    host = $3
WHERE id = $1
RETURNING id, owner_id, host, api_key
`

type UpdateProwlarrConfigurationParams struct {
	ID     string
	ApiKey string
	Host   string
}

func (q *Queries) UpdateProwlarrConfiguration(ctx context.Context, arg UpdateProwlarrConfigurationParams) (ProwlarrConfiguration, error) {
	row := q.db.QueryRow(ctx, updateProwlarrConfiguration, arg.ID, arg.ApiKey, arg.Host)
	var i ProwlarrConfiguration
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Host,
		&i.ApiKey,
	)
	return i, err
}

const updateTorrentClientCredentials = `-- name: UpdateTorrentClientCredentials :one
UPDATE torrent_clients
SET username = $2, password = $3
WHERE host = $1
RETURNING id, owner_id, source, host, username, password
`

type UpdateTorrentClientCredentialsParams struct {
	Host     string
	Username string
	Password string
}

func (q *Queries) UpdateTorrentClientCredentials(ctx context.Context, arg UpdateTorrentClientCredentialsParams) (TorrentClient, error) {
	row := q.db.QueryRow(ctx, updateTorrentClientCredentials, arg.Host, arg.Username, arg.Password)
	var i TorrentClient
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Source,
		&i.Host,
		&i.Username,
		&i.Password,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users 
SET password_hash = $2 
WHERE id = $1 
RETURNING id, username, password_hash
`

type UpdateUserPasswordParams struct {
	ID           string
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}
