// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: seasons.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSeason = `-- name: CreateSeason :one
INSERT INTO seasons (
    id, media_id, number, airing_status, metadata
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, media_id, number, airing_status, metadata
`

type CreateSeasonParams struct {
	ID           string
	MediaID      string
	Number       int32
	AiringStatus pgtype.Text
	Metadata     []byte
}

func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, createSeason,
		arg.ID,
		arg.MediaID,
		arg.Number,
		arg.AiringStatus,
		arg.Metadata,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.Number,
		&i.AiringStatus,
		&i.Metadata,
	)
	return i, err
}

const deleteSeason = `-- name: DeleteSeason :exec
DELETE FROM seasons WHERE id = $1
`

func (q *Queries) DeleteSeason(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSeason, id)
	return err
}

const getSeason = `-- name: GetSeason :one
SELECT id, media_id, number, airing_status, metadata FROM seasons 
WHERE id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetSeason(ctx context.Context, id string) (Season, error) {
	row := q.db.QueryRow(ctx, getSeason, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.Number,
		&i.AiringStatus,
		&i.Metadata,
	)
	return i, err
}

const getSeasonByNumber = `-- name: GetSeasonByNumber :one
SELECT id, media_id, number, airing_status, metadata FROM seasons 
WHERE media_id = $1 AND number = $2 LIMIT 1
`

type GetSeasonByNumberParams struct {
	MediaID string
	Number  int32
}

// Useful for finding "Season 2" of a specific show
func (q *Queries) GetSeasonByNumber(ctx context.Context, arg GetSeasonByNumberParams) (Season, error) {
	row := q.db.QueryRow(ctx, getSeasonByNumber, arg.MediaID, arg.Number)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.Number,
		&i.AiringStatus,
		&i.Metadata,
	)
	return i, err
}

const listSeasonsByMedia = `-- name: ListSeasonsByMedia :many
SELECT id, media_id, number, airing_status, metadata FROM seasons 
WHERE media_id = $1 
ORDER BY number ASC
`

func (q *Queries) ListSeasonsByMedia(ctx context.Context, mediaID string) ([]Season, error) {
	rows, err := q.db.Query(ctx, listSeasonsByMedia, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.Number,
			&i.AiringStatus,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeasonMetadata = `-- name: UpdateSeasonMetadata :one
UPDATE seasons
SET 
    airing_status = $2,
    metadata = $3
WHERE id = $1
RETURNING id, media_id, number, airing_status, metadata
`

type UpdateSeasonMetadataParams struct {
	ID           string
	AiringStatus pgtype.Text
	Metadata     []byte
}

func (q *Queries) UpdateSeasonMetadata(ctx context.Context, arg UpdateSeasonMetadataParams) (Season, error) {
	row := q.db.QueryRow(ctx, updateSeasonMetadata, arg.ID, arg.AiringStatus, arg.Metadata)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.Number,
		&i.AiringStatus,
		&i.Metadata,
	)
	return i, err
}
