// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: userSetup.sql

package sqlcgen

import (
	"context"

	shared "github.com/sonalys/animeman/internal/domain/shared"
)

const completeUserSetup = `-- name: CompleteUserSetup :exec
UPDATE user_setup SET is_completed = true WHERE user_id = $1
`

func (q *Queries) CompleteUserSetup(ctx context.Context, userID shared.ID) error {
	_, err := q.db.Exec(ctx, completeUserSetup, userID)
	return err
}

const isUserSetupComplete = `-- name: IsUserSetupComplete :one
SELECT is_completed FROM user_setup WHERE user_id = $1
`

func (q *Queries) IsUserSetupComplete(ctx context.Context, userID shared.ID) (bool, error) {
	row := q.db.QueryRow(ctx, isUserSetupComplete, userID)
	var is_completed bool
	err := row.Scan(&is_completed)
	return is_completed, err
}
