// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watchlist.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	shared "github.com/sonalys/animeman/internal/domain/shared"
)

const createWatchlist = `-- name: CreateWatchlist :one
INSERT INTO watchlists (
    id,
    owner_id, 
    source, 
    external_id, 
    sync_frequency,
    created_at
) VALUES (
    $1,
    $2, 
    $3::watchlist_source, 
    $4, 
    $5,
    $6
) RETURNING id, owner_id, source, external_id, sync_frequency, last_synced_at, created_at
`

type CreateWatchlistParams struct {
	ID            shared.ID
	OwnerID       shared.ID
	Source        WatchlistSource
	ExternalID    pgtype.Text
	SyncFrequency pgtype.Interval
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateWatchlist(ctx context.Context, arg CreateWatchlistParams) (Watchlist, error) {
	row := q.db.QueryRow(ctx, createWatchlist,
		arg.ID,
		arg.OwnerID,
		arg.Source,
		arg.ExternalID,
		arg.SyncFrequency,
		arg.CreatedAt,
	)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Source,
		&i.ExternalID,
		&i.SyncFrequency,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWatchlistEntry = `-- name: CreateWatchlistEntry :one
INSERT INTO watchlist_entries (
    watchlist_id, 
    media_id, 
    season_id, 
    last_watched_id, 
    status
) VALUES (
    $1, 
    $2, 
    $3, 
    $4, 
    $5::watchlist_status
)
RETURNING id, watchlist_id, media_id, season_id, last_watched_id, status, created_at, updated_at
`

type CreateWatchlistEntryParams struct {
	WatchlistID   shared.ID
	MediaID       shared.ID
	SeasonID      shared.ID
	LastWatchedID shared.ID
	Status        WatchlistStatus
}

func (q *Queries) CreateWatchlistEntry(ctx context.Context, arg CreateWatchlistEntryParams) (WatchlistEntry, error) {
	row := q.db.QueryRow(ctx, createWatchlistEntry,
		arg.WatchlistID,
		arg.MediaID,
		arg.SeasonID,
		arg.LastWatchedID,
		arg.Status,
	)
	var i WatchlistEntry
	err := row.Scan(
		&i.ID,
		&i.WatchlistID,
		&i.MediaID,
		&i.SeasonID,
		&i.LastWatchedID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWatchlist = `-- name: DeleteWatchlist :exec
DELETE FROM watchlists
WHERE id = $1
`

func (q *Queries) DeleteWatchlist(ctx context.Context, id shared.ID) error {
	_, err := q.db.Exec(ctx, deleteWatchlist, id)
	return err
}

const deleteWatchlistEntry = `-- name: DeleteWatchlistEntry :exec
DELETE FROM watchlist_entries
WHERE id = $1
`

func (q *Queries) DeleteWatchlistEntry(ctx context.Context, id shared.ID) error {
	_, err := q.db.Exec(ctx, deleteWatchlistEntry, id)
	return err
}

const getWatchlistByID = `-- name: GetWatchlistByID :one
SELECT id, owner_id, source, external_id, sync_frequency, last_synced_at, created_at FROM watchlists
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWatchlistByID(ctx context.Context, id shared.ID) (Watchlist, error) {
	row := q.db.QueryRow(ctx, getWatchlistByID, id)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Source,
		&i.ExternalID,
		&i.SyncFrequency,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWatchlistEntries = `-- name: GetWatchlistEntries :many
SELECT id, watchlist_id, media_id, season_id, last_watched_id, status, created_at, updated_at FROM watchlist_entries
WHERE watchlist_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) GetWatchlistEntries(ctx context.Context, watchlistID shared.ID) ([]WatchlistEntry, error) {
	rows, err := q.db.Query(ctx, getWatchlistEntries, watchlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchlistEntry
	for rows.Next() {
		var i WatchlistEntry
		if err := rows.Scan(
			&i.ID,
			&i.WatchlistID,
			&i.MediaID,
			&i.SeasonID,
			&i.LastWatchedID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchlistsByOwner = `-- name: ListWatchlistsByOwner :many
SELECT id, owner_id, source, external_id, sync_frequency, last_synced_at, created_at FROM watchlists
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWatchlistsByOwner(ctx context.Context, ownerID shared.ID) ([]Watchlist, error) {
	rows, err := q.db.Query(ctx, listWatchlistsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Watchlist
	for rows.Next() {
		var i Watchlist
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Source,
			&i.ExternalID,
			&i.SyncFrequency,
			&i.LastSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWatchlistSync = `-- name: UpdateWatchlistSync :one
UPDATE watchlists
SET 
    last_synced_at = NOW(),
    sync_frequency = $1
WHERE id = $2
RETURNING id, owner_id, source, external_id, sync_frequency, last_synced_at, created_at
`

type UpdateWatchlistSyncParams struct {
	SyncFrequency pgtype.Interval
	ID            shared.ID
}

func (q *Queries) UpdateWatchlistSync(ctx context.Context, arg UpdateWatchlistSyncParams) (Watchlist, error) {
	row := q.db.QueryRow(ctx, updateWatchlistSync, arg.SyncFrequency, arg.ID)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Source,
		&i.ExternalID,
		&i.SyncFrequency,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}
