version: 2

release:
  draft: true
  replace_existing_draft: true

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/service
    binary: animeman
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

dockers_v2:
  - dockerfile: Dockerfile
    images:
      - "ghcr.io/sonalys/animeman"
    tags:
      - "v{{ .Version }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
      - "v{{ .Major }}"
