// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"fmt"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *ErrorResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Authentication
type Authentication struct {
	Type  AuthenticationType `json:"type"`
	OneOf AuthenticationSum
}

// GetType returns the value of Type.
func (s *Authentication) GetType() AuthenticationType {
	return s.Type
}

// GetOneOf returns the value of OneOf.
func (s *Authentication) GetOneOf() AuthenticationSum {
	return s.OneOf
}

// SetType sets the value of Type.
func (s *Authentication) SetType(val AuthenticationType) {
	s.Type = val
}

// SetOneOf sets the value of OneOf.
func (s *Authentication) SetOneOf(val AuthenticationSum) {
	s.OneOf = val
}

// Ref: #/components/schemas/AuthenticationAPIKey
type AuthenticationAPIKey struct {
	Key string `json:"key"`
}

// GetKey returns the value of Key.
func (s *AuthenticationAPIKey) GetKey() string {
	return s.Key
}

// SetKey sets the value of Key.
func (s *AuthenticationAPIKey) SetKey(val string) {
	s.Key = val
}

// AuthenticationLoginNoContent is response for AuthenticationLogin operation.
type AuthenticationLoginNoContent struct {
	SetCookie string
}

// GetSetCookie returns the value of SetCookie.
func (s *AuthenticationLoginNoContent) GetSetCookie() string {
	return s.SetCookie
}

// SetSetCookie sets the value of SetCookie.
func (s *AuthenticationLoginNoContent) SetSetCookie(val string) {
	s.SetCookie = val
}

type AuthenticationLoginReq struct {
	// User's username address.
	Username string `json:"username"`
	// User's password.
	Password string `json:"password"`
}

// GetUsername returns the value of Username.
func (s *AuthenticationLoginReq) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *AuthenticationLoginReq) GetPassword() string {
	return s.Password
}

// SetUsername sets the value of Username.
func (s *AuthenticationLoginReq) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *AuthenticationLoginReq) SetPassword(val string) {
	s.Password = val
}

// AuthenticationSum represents sum type.
type AuthenticationSum struct {
	Type                       AuthenticationSumType // switch on this field
	AuthenticationUserPassword AuthenticationUserPassword
	AuthenticationAPIKey       AuthenticationAPIKey
}

// AuthenticationSumType is oneOf type of AuthenticationSum.
type AuthenticationSumType string

// Possible values for AuthenticationSumType.
const (
	AuthenticationUserPasswordAuthenticationSum AuthenticationSumType = "AuthenticationUserPassword"
	AuthenticationAPIKeyAuthenticationSum       AuthenticationSumType = "AuthenticationAPIKey"
)

// IsAuthenticationUserPassword reports whether AuthenticationSum is AuthenticationUserPassword.
func (s AuthenticationSum) IsAuthenticationUserPassword() bool {
	return s.Type == AuthenticationUserPasswordAuthenticationSum
}

// IsAuthenticationAPIKey reports whether AuthenticationSum is AuthenticationAPIKey.
func (s AuthenticationSum) IsAuthenticationAPIKey() bool {
	return s.Type == AuthenticationAPIKeyAuthenticationSum
}

// SetAuthenticationUserPassword sets AuthenticationSum to AuthenticationUserPassword.
func (s *AuthenticationSum) SetAuthenticationUserPassword(v AuthenticationUserPassword) {
	s.Type = AuthenticationUserPasswordAuthenticationSum
	s.AuthenticationUserPassword = v
}

// GetAuthenticationUserPassword returns AuthenticationUserPassword and true boolean if AuthenticationSum is AuthenticationUserPassword.
func (s AuthenticationSum) GetAuthenticationUserPassword() (v AuthenticationUserPassword, ok bool) {
	if !s.IsAuthenticationUserPassword() {
		return v, false
	}
	return s.AuthenticationUserPassword, true
}

// NewAuthenticationUserPasswordAuthenticationSum returns new AuthenticationSum from AuthenticationUserPassword.
func NewAuthenticationUserPasswordAuthenticationSum(v AuthenticationUserPassword) AuthenticationSum {
	var s AuthenticationSum
	s.SetAuthenticationUserPassword(v)
	return s
}

// SetAuthenticationAPIKey sets AuthenticationSum to AuthenticationAPIKey.
func (s *AuthenticationSum) SetAuthenticationAPIKey(v AuthenticationAPIKey) {
	s.Type = AuthenticationAPIKeyAuthenticationSum
	s.AuthenticationAPIKey = v
}

// GetAuthenticationAPIKey returns AuthenticationAPIKey and true boolean if AuthenticationSum is AuthenticationAPIKey.
func (s AuthenticationSum) GetAuthenticationAPIKey() (v AuthenticationAPIKey, ok bool) {
	if !s.IsAuthenticationAPIKey() {
		return v, false
	}
	return s.AuthenticationAPIKey, true
}

// NewAuthenticationAPIKeyAuthenticationSum returns new AuthenticationSum from AuthenticationAPIKey.
func NewAuthenticationAPIKeyAuthenticationSum(v AuthenticationAPIKey) AuthenticationSum {
	var s AuthenticationSum
	s.SetAuthenticationAPIKey(v)
	return s
}

type AuthenticationType string

const (
	AuthenticationTypeUserPassword AuthenticationType = "userPassword"
	AuthenticationTypeApiKey       AuthenticationType = "apiKey"
)

// AllValues returns all AuthenticationType values.
func (AuthenticationType) AllValues() []AuthenticationType {
	return []AuthenticationType{
		AuthenticationTypeUserPassword,
		AuthenticationTypeApiKey,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AuthenticationType) MarshalText() ([]byte, error) {
	switch s {
	case AuthenticationTypeUserPassword:
		return []byte(s), nil
	case AuthenticationTypeApiKey:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AuthenticationType) UnmarshalText(data []byte) error {
	switch AuthenticationType(data) {
	case AuthenticationTypeUserPassword:
		*s = AuthenticationTypeUserPassword
		return nil
	case AuthenticationTypeApiKey:
		*s = AuthenticationTypeApiKey
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/AuthenticationUserPassword
type AuthenticationUserPassword struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// GetUsername returns the value of Username.
func (s *AuthenticationUserPassword) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *AuthenticationUserPassword) GetPassword() string {
	return s.Password
}

// SetUsername sets the value of Username.
func (s *AuthenticationUserPassword) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *AuthenticationUserPassword) SetPassword(val string) {
	s.Password = val
}

type AuthenticationWhoAmIOK struct {
	UserID uuid.UUID `json:"userID"`
}

// GetUserID returns the value of UserID.
func (s *AuthenticationWhoAmIOK) GetUserID() uuid.UUID {
	return s.UserID
}

// SetUserID sets the value of UserID.
func (s *AuthenticationWhoAmIOK) SetUserID(val uuid.UUID) {
	s.UserID = val
}

type CookieAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *CookieAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *CookieAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *CookieAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *CookieAuth) SetRoles(val []string) {
	s.Roles = val
}

type ErrorResponse struct {
	// Unique identifier for the error instance.
	TraceID     OptUUID      `json:"traceID"`
	Details     OptString    `json:"details"`
	FieldErrors []FieldError `json:"fieldErrors"`
}

// GetTraceID returns the value of TraceID.
func (s *ErrorResponse) GetTraceID() OptUUID {
	return s.TraceID
}

// GetDetails returns the value of Details.
func (s *ErrorResponse) GetDetails() OptString {
	return s.Details
}

// GetFieldErrors returns the value of FieldErrors.
func (s *ErrorResponse) GetFieldErrors() []FieldError {
	return s.FieldErrors
}

// SetTraceID sets the value of TraceID.
func (s *ErrorResponse) SetTraceID(val OptUUID) {
	s.TraceID = val
}

// SetDetails sets the value of Details.
func (s *ErrorResponse) SetDetails(val OptString) {
	s.Details = val
}

// SetFieldErrors sets the value of FieldErrors.
func (s *ErrorResponse) SetFieldErrors(val []FieldError) {
	s.FieldErrors = val
}

// ErrorResponseStatusCode wraps ErrorResponse with StatusCode.
type ErrorResponseStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorResponseStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorResponseStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// Ref: #/components/schemas/FieldError
type FieldError struct {
	Field string         `json:"field"`
	Code  FieldErrorCode `json:"code"`
	// Human readable error message.
	Message string `json:"message"`
}

// GetField returns the value of Field.
func (s *FieldError) GetField() string {
	return s.Field
}

// GetCode returns the value of Code.
func (s *FieldError) GetCode() FieldErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *FieldError) GetMessage() string {
	return s.Message
}

// SetField sets the value of Field.
func (s *FieldError) SetField(val string) {
	s.Field = val
}

// SetCode sets the value of Code.
func (s *FieldError) SetCode(val FieldErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *FieldError) SetMessage(val string) {
	s.Message = val
}

type FieldErrorCode string

const (
	FieldErrorCodeAlreadyExists FieldErrorCode = "alreadyExists"
	FieldErrorCodeMinLength     FieldErrorCode = "minLength"
	FieldErrorCodeMaxLength     FieldErrorCode = "maxLength"
	FieldErrorCodeRequired      FieldErrorCode = "required"
	FieldErrorCodeInvalidFormat FieldErrorCode = "invalidFormat"
	FieldErrorCodeUnknown       FieldErrorCode = "unknown"
)

// AllValues returns all FieldErrorCode values.
func (FieldErrorCode) AllValues() []FieldErrorCode {
	return []FieldErrorCode{
		FieldErrorCodeAlreadyExists,
		FieldErrorCodeMinLength,
		FieldErrorCodeMaxLength,
		FieldErrorCodeRequired,
		FieldErrorCodeInvalidFormat,
		FieldErrorCodeUnknown,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s FieldErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case FieldErrorCodeAlreadyExists:
		return []byte(s), nil
	case FieldErrorCodeMinLength:
		return []byte(s), nil
	case FieldErrorCodeMaxLength:
		return []byte(s), nil
	case FieldErrorCodeRequired:
		return []byte(s), nil
	case FieldErrorCodeInvalidFormat:
		return []byte(s), nil
	case FieldErrorCodeUnknown:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *FieldErrorCode) UnmarshalText(data []byte) error {
	switch FieldErrorCode(data) {
	case FieldErrorCodeAlreadyExists:
		*s = FieldErrorCodeAlreadyExists
		return nil
	case FieldErrorCodeMinLength:
		*s = FieldErrorCodeMinLength
		return nil
	case FieldErrorCodeMaxLength:
		*s = FieldErrorCodeMaxLength
		return nil
	case FieldErrorCodeRequired:
		*s = FieldErrorCodeRequired
		return nil
	case FieldErrorCodeInvalidFormat:
		*s = FieldErrorCodeInvalidFormat
		return nil
	case FieldErrorCodeUnknown:
		*s = FieldErrorCodeUnknown
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Indexer
type Indexer struct {
	ID   uuid.UUID   `json:"id"`
	Type IndexerType `json:"type"`
	URL  url.URL     `json:"url"`
}

// GetID returns the value of ID.
func (s *Indexer) GetID() uuid.UUID {
	return s.ID
}

// GetType returns the value of Type.
func (s *Indexer) GetType() IndexerType {
	return s.Type
}

// GetURL returns the value of URL.
func (s *Indexer) GetURL() url.URL {
	return s.URL
}

// SetID sets the value of ID.
func (s *Indexer) SetID(val uuid.UUID) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *Indexer) SetType(val IndexerType) {
	s.Type = val
}

// SetURL sets the value of URL.
func (s *Indexer) SetURL(val url.URL) {
	s.URL = val
}

// Ref: #/components/schemas/IndexerConfig
type IndexerConfig struct {
	Type IndexerType    `json:"type"`
	URL  url.URL        `json:"url"`
	Auth Authentication `json:"auth"`
}

// GetType returns the value of Type.
func (s *IndexerConfig) GetType() IndexerType {
	return s.Type
}

// GetURL returns the value of URL.
func (s *IndexerConfig) GetURL() url.URL {
	return s.URL
}

// GetAuth returns the value of Auth.
func (s *IndexerConfig) GetAuth() Authentication {
	return s.Auth
}

// SetType sets the value of Type.
func (s *IndexerConfig) SetType(val IndexerType) {
	s.Type = val
}

// SetURL sets the value of URL.
func (s *IndexerConfig) SetURL(val url.URL) {
	s.URL = val
}

// SetAuth sets the value of Auth.
func (s *IndexerConfig) SetAuth(val Authentication) {
	s.Auth = val
}

// Ref: #/components/schemas/IndexerType
type IndexerType string

const (
	IndexerTypeProwlarr IndexerType = "prowlarr"
	IndexerTypeJackett  IndexerType = "jackett"
	IndexerTypeTorznab  IndexerType = "torznab"
)

// AllValues returns all IndexerType values.
func (IndexerType) AllValues() []IndexerType {
	return []IndexerType{
		IndexerTypeProwlarr,
		IndexerTypeJackett,
		IndexerTypeTorznab,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s IndexerType) MarshalText() ([]byte, error) {
	switch s {
	case IndexerTypeProwlarr:
		return []byte(s), nil
	case IndexerTypeJackett:
		return []byte(s), nil
	case IndexerTypeTorznab:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *IndexerType) UnmarshalText(data []byte) error {
	switch IndexerType(data) {
	case IndexerTypeProwlarr:
		*s = IndexerTypeProwlarr
		return nil
	case IndexerTypeJackett:
		*s = IndexerTypeJackett
		return nil
	case IndexerTypeTorznab:
		*s = IndexerTypeTorznab
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type IndexersPostCreated struct {
	ID uuid.UUID `json:"id"`
}

// GetID returns the value of ID.
func (s *IndexersPostCreated) GetID() uuid.UUID {
	return s.ID
}

// SetID sets the value of ID.
func (s *IndexersPostCreated) SetID(val uuid.UUID) {
	s.ID = val
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// RegisterUserBadRequest is response for RegisterUser operation.
type RegisterUserBadRequest struct{}

func (*RegisterUserBadRequest) registerUserRes() {}

// RegisterUserConflict is response for RegisterUser operation.
type RegisterUserConflict struct{}

func (*RegisterUserConflict) registerUserRes() {}

type RegisterUserCreated struct {
	ID uuid.UUID `json:"id"`
}

// GetID returns the value of ID.
func (s *RegisterUserCreated) GetID() uuid.UUID {
	return s.ID
}

// SetID sets the value of ID.
func (s *RegisterUserCreated) SetID(val uuid.UUID) {
	s.ID = val
}

// RegisterUserCreatedHeaders wraps RegisterUserCreated with response headers.
type RegisterUserCreatedHeaders struct {
	SetCookie string
	Response  RegisterUserCreated
}

// GetSetCookie returns the value of SetCookie.
func (s *RegisterUserCreatedHeaders) GetSetCookie() string {
	return s.SetCookie
}

// GetResponse returns the value of Response.
func (s *RegisterUserCreatedHeaders) GetResponse() RegisterUserCreated {
	return s.Response
}

// SetSetCookie sets the value of SetCookie.
func (s *RegisterUserCreatedHeaders) SetSetCookie(val string) {
	s.SetCookie = val
}

// SetResponse sets the value of Response.
func (s *RegisterUserCreatedHeaders) SetResponse(val RegisterUserCreated) {
	s.Response = val
}

func (*RegisterUserCreatedHeaders) registerUserRes() {}

// Ref: #/components/schemas/UserRegistration
type UserRegistration struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// GetUsername returns the value of Username.
func (s *UserRegistration) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *UserRegistration) GetPassword() string {
	return s.Password
}

// SetUsername sets the value of Username.
func (s *UserRegistration) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *UserRegistration) SetPassword(val string) {
	s.Password = val
}
