// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"fmt"

	"github.com/google/uuid"
)

func (s *ErrorResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Error
type Error struct {
	Code string `json:"code"`
	// Human readable error message.
	Message  string           `json:"message"`
	Metadata OptErrorMetadata `json:"metadata"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// GetMetadata returns the value of Metadata.
func (s *Error) GetMetadata() OptErrorMetadata {
	return s.Metadata
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// SetMetadata sets the value of Metadata.
func (s *Error) SetMetadata(val OptErrorMetadata) {
	s.Metadata = val
}

// Ref: #/components/schemas/ErrorMetadata
type ErrorMetadata struct {
	Field OptString `json:"field"`
}

// GetField returns the value of Field.
func (s *ErrorMetadata) GetField() OptString {
	return s.Field
}

// SetField sets the value of Field.
func (s *ErrorMetadata) SetField(val OptString) {
	s.Field = val
}

type ErrorResponse struct {
	// Unique identifier for the error instance.
	TraceID uuid.UUID `json:"trace_id"`
	Errors  []Error   `json:"errors"`
}

// GetTraceID returns the value of TraceID.
func (s *ErrorResponse) GetTraceID() uuid.UUID {
	return s.TraceID
}

// GetErrors returns the value of Errors.
func (s *ErrorResponse) GetErrors() []Error {
	return s.Errors
}

// SetTraceID sets the value of TraceID.
func (s *ErrorResponse) SetTraceID(val uuid.UUID) {
	s.TraceID = val
}

// SetErrors sets the value of Errors.
func (s *ErrorResponse) SetErrors(val []Error) {
	s.Errors = val
}

// ErrorResponseStatusCode wraps ErrorResponse with StatusCode.
type ErrorResponseStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorResponseStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorResponseStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// NewOptErrorMetadata returns new OptErrorMetadata with value set to v.
func NewOptErrorMetadata(v ErrorMetadata) OptErrorMetadata {
	return OptErrorMetadata{
		Value: v,
		Set:   true,
	}
}

// OptErrorMetadata is optional ErrorMetadata.
type OptErrorMetadata struct {
	Value ErrorMetadata
	Set   bool
}

// IsSet returns true if OptErrorMetadata was set.
func (o OptErrorMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptErrorMetadata) Reset() {
	var v ErrorMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptErrorMetadata) SetTo(v ErrorMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptErrorMetadata) Get() (v ErrorMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptErrorMetadata) Or(d ErrorMetadata) ErrorMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// RegisterUserBadRequest is response for RegisterUser operation.
type RegisterUserBadRequest struct{}

func (*RegisterUserBadRequest) registerUserRes() {}

// RegisterUserConflict is response for RegisterUser operation.
type RegisterUserConflict struct{}

func (*RegisterUserConflict) registerUserRes() {}

type RegisterUserCreated struct {
	ID OptUUID `json:"id"`
}

// GetID returns the value of ID.
func (s *RegisterUserCreated) GetID() OptUUID {
	return s.ID
}

// SetID sets the value of ID.
func (s *RegisterUserCreated) SetID(val OptUUID) {
	s.ID = val
}

// RegisterUserCreatedHeaders wraps RegisterUserCreated with response headers.
type RegisterUserCreatedHeaders struct {
	SetCookie OptString
	Response  RegisterUserCreated
}

// GetSetCookie returns the value of SetCookie.
func (s *RegisterUserCreatedHeaders) GetSetCookie() OptString {
	return s.SetCookie
}

// GetResponse returns the value of Response.
func (s *RegisterUserCreatedHeaders) GetResponse() RegisterUserCreated {
	return s.Response
}

// SetSetCookie sets the value of SetCookie.
func (s *RegisterUserCreatedHeaders) SetSetCookie(val OptString) {
	s.SetCookie = val
}

// SetResponse sets the value of Response.
func (s *RegisterUserCreatedHeaders) SetResponse(val RegisterUserCreated) {
	s.Response = val
}

func (*RegisterUserCreatedHeaders) registerUserRes() {}

// Ref: #/components/schemas/UserRegistration
type UserRegistration struct {
	// Must be alphanumeric and 3-20 characters long.
	Username string `json:"username"`
	// Must be at least 8 characters long.
	Password string `json:"password"`
}

// GetUsername returns the value of Username.
func (s *UserRegistration) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *UserRegistration) GetPassword() string {
	return s.Password
}

// SetUsername sets the value of Username.
func (s *UserRegistration) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *UserRegistration) SetPassword(val string) {
	s.Password = val
}
