// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AuthenticationLogin implements AuthenticationLogin operation.
//
// Authenticate as the specified identity.
//
// POST /authentication/login
func (UnimplementedHandler) AuthenticationLogin(ctx context.Context, req *AuthenticationLoginReq) (r *AuthenticationLoginNoContent, _ error) {
	return r, ht.ErrNotImplemented
}

// AuthenticationWhoAmI implements AuthenticationWhoAmI operation.
//
// Returns current information on the authenticated entity.
//
// GET /authentication/whoami
func (UnimplementedHandler) AuthenticationWhoAmI(ctx context.Context) (r *AuthenticationWhoAmIOK, _ error) {
	return r, ht.ErrNotImplemented
}

// IndexingClientsGet implements GET /indexing-clients operation.
//
// List all configured indexers.
//
// GET /indexing-clients
func (UnimplementedHandler) IndexingClientsGet(ctx context.Context) (r []Indexer, _ error) {
	return r, ht.ErrNotImplemented
}

// IndexingClientsPost implements POST /indexing-clients operation.
//
// Add a new indexer.
//
// POST /indexing-clients
func (UnimplementedHandler) IndexingClientsPost(ctx context.Context, req *IndexerConfig) (r *IndexingClientsPostCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterUser implements registerUser operation.
//
// Creates a new user account with a unique username and a secure password.
//
// POST /register
func (UnimplementedHandler) RegisterUser(ctx context.Context, req *UserRegistration) (r RegisterUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TestIndexingClientConfiguration implements TestIndexingClientConfiguration operation.
//
// Tests an indexing client configuration.
//
// POST /indexing-clients/test
func (UnimplementedHandler) TestIndexingClientConfiguration(ctx context.Context, req *IndexerConfig) error {
	return ht.ErrNotImplemented
}

// TestTransferClientConfiguration implements TestTransferClientConfiguration operation.
//
// Tests a transfer client configuration.
//
// POST /transfer-clients/test
func (UnimplementedHandler) TestTransferClientConfiguration(ctx context.Context, req *TransferClientConfig) error {
	return ht.ErrNotImplemented
}

// NewError creates *ErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResponseStatusCode) {
	r = new(ErrorResponseStatusCode)
	return r
}
