// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	AuthenticationLoginOperation             OperationName = "AuthenticationLogin"
	AuthenticationWhoAmIOperation            OperationName = "AuthenticationWhoAmI"
	IndexersGetOperation                     OperationName = "IndexersGet"
	IndexersPostOperation                    OperationName = "IndexersPost"
	RegisterUserOperation                    OperationName = "RegisterUser"
	TestTransferClientConfigurationOperation OperationName = "TestTransferClientConfiguration"
)
