// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	UsersHandler
	// IndexingClientsGet implements GET /indexing-clients operation.
	//
	// List all configured indexers.
	//
	// GET /indexing-clients
	IndexingClientsGet(ctx context.Context) ([]Indexer, error)
	// IndexingClientsPost implements POST /indexing-clients operation.
	//
	// Add a new indexer.
	//
	// POST /indexing-clients
	IndexingClientsPost(ctx context.Context, req *IndexerConfig) (*IndexingClientsPostCreated, error)
	// RegisterUser implements registerUser operation.
	//
	// Creates a new user account with a unique username and a secure password.
	//
	// POST /register
	RegisterUser(ctx context.Context, req *UserRegistration) (RegisterUserRes, error)
	// SetupGet implements GET /setup operation.
	//
	// Gets the initial configuration progress.
	//
	// GET /setup
	SetupGet(ctx context.Context) (*SetupGetOK, error)
	// TestIndexingClientConfiguration implements TestIndexingClientConfiguration operation.
	//
	// Tests an indexing client configuration.
	//
	// POST /indexing-clients/test
	TestIndexingClientConfiguration(ctx context.Context, req *IndexerConfig) error
	// TestTransferClientConfiguration implements TestTransferClientConfiguration operation.
	//
	// Tests a transfer client configuration.
	//
	// POST /transfer-clients/test
	TestTransferClientConfiguration(ctx context.Context, req *TransferClientConfig) error
	// TransferClientsGet implements GET /transfer-clients operation.
	//
	// Lists all configured transfer clients.
	//
	// GET /transfer-clients
	TransferClientsGet(ctx context.Context) ([]TransferClient, error)
	// TransferClientsPost implements POST /transfer-clients operation.
	//
	// Add a new indexer.
	//
	// POST /transfer-clients
	TransferClientsPost(ctx context.Context, req *TransferClientConfig) (*TransferClientsPostCreated, error)
	// NewError creates *ErrorResponseStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorResponseStatusCode
}

// UsersHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Users
type UsersHandler interface {
	// AuthenticationLogin implements AuthenticationLogin operation.
	//
	// Authenticate as the specified identity.
	//
	// POST /authentication/login
	AuthenticationLogin(ctx context.Context, req *AuthenticationLoginReq) (*AuthenticationLoginNoContent, error)
	// AuthenticationWhoAmI implements AuthenticationWhoAmI operation.
	//
	// Returns current information on the authenticated entity.
	//
	// GET /authentication/whoami
	AuthenticationWhoAmI(ctx context.Context) (*AuthenticationWhoAmIOK, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
