// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	UsersHandler
	// IndexersGet implements GET /indexers operation.
	//
	// List all configured indexers.
	//
	// GET /indexers
	IndexersGet(ctx context.Context) ([]Indexer, error)
	// IndexersPost implements POST /indexers operation.
	//
	// Add a new indexer.
	//
	// POST /indexers
	IndexersPost(ctx context.Context, req *IndexerConfig) (*IndexersPostCreated, error)
	// RegisterUser implements registerUser operation.
	//
	// Creates a new user account with a unique username and a secure password.
	//
	// POST /register
	RegisterUser(ctx context.Context, req *UserRegistration) (RegisterUserRes, error)
	// NewError creates *ErrorResponseStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorResponseStatusCode
}

// UsersHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Users
type UsersHandler interface {
	// AuthenticationLogin implements AuthenticationLogin operation.
	//
	// Authenticate as the specified identity.
	//
	// POST /authentication/login
	AuthenticationLogin(ctx context.Context, req *AuthenticationLoginReq) (*AuthenticationLoginOK, error)
	// AuthenticationWhoAmI implements AuthenticationWhoAmI operation.
	//
	// Returns current information on the authenticated entity.
	//
	// GET /authentication/whoami
	AuthenticationWhoAmI(ctx context.Context) (*AuthenticationWhoAmIOK, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
