generator:
  # sets generator features.
  features:
    enable:
      # Enables validation of client requests
      - "client/request/validation"
      # Enables validation of server responses
      - "server/response/validation"
      # Enables OpenTelemetry integration
      - "ogen/otel"
      # Enables stub Handler generation
      - "ogen/unimplemented"

  # functions to ignore
  ignore_not_implemented: ["all"]
