FROM alpine:3.6 as alpine

RUN apk add -U --no-cache ca-certificates

FROM scratch

COPY ./builders/passwd /etc/passwd
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY bin/linux/amd64/animeman /animeman

USER nobody

ENTRYPOINT ["/animeman"]