openapi: 3.1.0
info:
  title: Animeman
  description: Your anime media collection overlord!
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Local Server

paths:
  /register:
    post:
      summary: Register a new user
      description: Creates a new user account with a unique username and a secure password.
      operationId: registerUser
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistration"
      responses:
        default:
          $ref: "#/components/responses/ErrorResponse"
        "201":
          description: User created successfully.
          headers:
            Set-Cookie:
              required: true
              description: Sets the session cookie
              schema:
                type: string
                example: SESSION_ID=abc12345; Path=/; HttpOnly; Secure
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                properties:
                  id:
                    type: string
                    format: uuid
        "400":
          description: Invalid input (e.g., password too weak).
        "409":
          description: Conflict (e.g., username already exists).

  /authentication/whoami:
    x-ogen-operation-group: Users
    get:
      operationId: AuthenticationWhoAmI
      description: returns current information on the authenticated entity
      security:
        - cookieAuth: []
      responses:
        default:
          $ref: "#/components/responses/ErrorResponse"
        "200":
          description: Caller is authenticated and the data is successfully retrieved
          content:
            application/json:
              schema:
                type: object
                required:
                  - userID
                properties:
                  userID:
                    type: string
                    format: uuid

  /authentication/login:
    x-ogen-operation-group: Users
    post:
      operationId: AuthenticationLogin
      description: Authenticate as the specified identity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: User's username address
                  example: "john.doe@example.com"
                password:
                  type: string
                  format: password
                  description: User's password
                  example: "P@ssw0rd"
                  minLength: 8
                  maxLength: 72
      responses:
        default:
          $ref: "#/components/responses/ErrorResponse"
        "204":
          description: Successfully authenticated
          headers:
            Set-Cookie:
              required: true
              schema:
                type: string
                example: SESSION_ID=abcde12345; Path=/; HttpOnly

  /indexers:
    get:
      summary: List all configured indexers
      tags:
        - Indexers
      security:
        - cookieAuth: []
      responses:
        "200":
          description: List of indexers retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Indexer"
        default:
          $ref: "#/components/responses/ErrorResponse"

    post:
      summary: Add a new indexer
      tags:
        - Indexers
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IndexerConfig"
      responses:
        "201":
          description: Indexer configured successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                properties:
                  id:
                    type: string
                    format: uuid
        default:
          $ref: "#/components/responses/ErrorResponse"

  /transfer-clients/test:
    post:
      operationId: TestTransferClientConfiguration
      description: Tests a transfer client configuration
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransferClientConfig"
      responses:
        default:
          $ref: "#/components/responses/ErrorResponse"
        "204":
          description: Valid configuration

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: SESSION_ID
  responses:
    ErrorResponse:
      description: An error has occurred
      content:
        application/json:
          schema:
            type: object
            properties:
              traceID:
                type: string
                format: uuid
                description: Unique identifier for the error instance
                example: "b6b7b3b0-1b4d-4f4b-8b3e-1b4d4f4b8b3e"
              details:
                type: string
              fieldErrors:
                type: array
                items:
                  $ref: "#/components/schemas/FieldError"
  schemas:
    IndexerClientType:
      type: string
      enum: [prowlarr]

    TransferClientType:
      type: string
      enum: [qbittorrent]

    TransferClientConfig:
      type: object
      required: [type, hostname, auth]
      properties:
        type:
          $ref: "#/components/schemas/TransferClientType"
        hostname:
          type: string
          format: uri
        auth:
          $ref: "#/components/schemas/Authentication"

    IndexerConfig:
      type: object
      required: [type, hostname, auth]
      properties:
        type:
          $ref: "#/components/schemas/IndexerClientType"
        hostname:
          type: string
          format: uri
        auth:
          $ref: "#/components/schemas/Authentication"

    Indexer:
      type: object
      required: [id, type, hostname]
      properties:
        id:
          type: string
          format: uuid
        type:
          $ref: "#/components/schemas/IndexerClientType"
        hostname:
          type: string
          format: uri

    Authentication:
      type: object
      required: [type]
      properties:
        type:
          type: string
          enum: [userPassword, apiKey]
      oneOf:
        - $ref: "#/components/schemas/AuthenticationUserPassword"
        - $ref: "#/components/schemas/AuthenticationAPIKey"

    AuthenticationUserPassword:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
        password:
          type: string
          format: password

    AuthenticationAPIKey:
      type: object
      required: [key]
      properties:
        key:
          type: string
          format: password

    FieldError:
      type: object
      required:
        - field
        - message
        - code
      properties:
        field:
          type: string
        code:
          type: string
          enum:
            - alreadyExists
            - minLength
            - maxLength
            - required
            - invalid
            - invalidFormat
            - unknown
        message:
          type: string
          description: Human readable error message
          example: "Invalid format"

    UserRegistration:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 20
          pattern: "^[a-zA-Z0-9_]+$"
          example: "jdoe_secure"
        password:
          type: string
          format: password
          minLength: 8
          maxLength: 72
          example: "P@ssw0rd123!"
